.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_CLIENT_COMMAND_SIMPLE" "3" "2016\(hy11\(hy07" "MongoDB C Driver"
.SH NAME
mongoc_client_command_simple() \- None
.SH "SYNOPSIS"

.nf
.nf
bool
mongoc_client_command_simple (mongoc_client_t           *client,
                              const char                *db_name,
                              const bson_t              *command,
                              const mongoc_read_prefs_t *read_prefs,
                              bson_t                    *reply,
                              bson_error_t              *error);
.fi
.fi

This is a simplified interface to
.B mongoc_client_command(3)
. It returns the first document from the result cursor into
.B reply
. The client's read preference, read concern, and write concern are not applied to the command.

.B NOTE
.RS
.B reply
is always set, and should be released with
.B bson_destroy(3)
.
.RE

.SH "PARAMETERS"

.TP
.B
client
A
.B mongoc_client_t
.
.LP
.TP
.B
db_name
The name of the database to run the command on.
.LP
.TP
.B
command
A
.B bson_t
containing the command specification.
.LP
.TP
.B
read_prefs
An optional
.B mongoc_read_prefs_t
. Otherwise, the command uses mode
.B MONGOC_READ_PRIMARY
.
.LP
.TP
.B
reply
A location for the resulting document.
.LP
.TP
.B
error
An optional location for a
.B bson_error_t
or
.B NULL
.
.LP

.SH "ERRORS"

Errors are propagated via the
.B error
parameter.

.SH "RETURNS"

.B true
if successful; otherwise
.B false
and
.B error
is set.

This function does not check the server response for a write concern error or write concern timeout.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.