.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_GRIDFS_FIND_WITH_OPTS" "3" "2016\(hy11\(hy08" "MongoDB C Driver"
.SH NAME
mongoc_gridfs_find_with_opts() \- Finds all gridfs files matching filter. You can iterate the matched gridfs files with the resulting file list.
.SH "SYNOPSIS"

.nf
.nf
mongoc_gridfs_file_list_t *
mongoc_gridfs_find_with_opts (mongoc_gridfs_t *gridfs,
                              const bson_t    *filter,
                              const bson_t    *opts)
   BSON_GNUC_WARN_UNUSED_RESULT;
.fi
.fi

.SH "PARAMETERS"

.TP
.B
gridfs
A
.B mongoc_gridfs_t
.
.LP
.TP
.B
filter
A
.B bson_t
containing the query to execute.
.LP
.TP
.B
opts
A
.B bson_t
query options, including sort order and which fields to return. Can be
.B NULL
.
.LP

.SH "DESCRIPTION"

Finds all gridfs files matching
.B filter
. You can iterate the matched gridfs files with the resulting file list.

See
.B mongoc_collection_find_with_opts
for a description of the
.B filter
and
.B opts
parameters.

.SH "RETURNS"

A newly allocated
.B mongoc_gridfs_file_list_t
that should be freed with
.B mongoc_gridfs_file_list_destroy(3)
when no longer in use.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.