.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_APM_SET_COMMAND_SUCCEEDED_CB" "3" "2016\(hy11\(hy07" "MongoDB C Driver"
.SH NAME
mongoc_apm_set_command_succeeded_cb() \- None
.SH "SYNOPSIS"

.nf
.nf
typedef void
(*mongoc_apm_command_succeeded_cb_t) (const mongoc_apm_command_succeeded_t *event);

void
mongoc_apm_set_command_succeeded_cb  (mongoc_apm_callbacks_t               *callbacks,
                                      mongoc_apm_command_succeeded_cb_t     cb);
.fi
.fi

Receive an event notification whenever the driver completes a MongoDB operation.

.SH "PARAMETERS"

.TP
.B
callbacks
A
.B mongoc_apm_callbacks_t
.
.LP
.TP
.B
cb
A function to call with a
.B mongoc_apm_command_succeeded_t
whenever the driver completes a MongoDB operation.
.LP

.SH "SEE ALSO"

.B Introduction to Application Performance Monitoring


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.